CREATE DATABASE IF NOT EXISTS inter;
USE inter;

CREATE TABLE IF NOT EXISTS UserMaster (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) not null,
email VARCHAR(255) not null,
status tinyint(1) not null DEFAULT '1',
dtCreation timestamp NULL DEFAULT CURRENT_TIMESTAMP,
dtUpdation timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS GroupMaster (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) not null,
status tinyint(1) not null DEFAULT '1',
dtCreation timestamp NULL DEFAULT CURRENT_TIMESTAMP,
dtUpdation timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS UserGroupMapping (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`uId` INT(11) NOT NULL,
`gId` INT(11) NOT NULL,
dtCreation timestamp NULL DEFAULT CURRENT_TIMESTAMP,
dtUpdation timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS EventStore (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`eventType` INT(11) NOT NULL,
`eventData` INT(11) NOT NULL,
dtCreation timestamp NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB AUTO_INCREMENT=1;
